language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- npm run build
after_script:
- cd travis
- touch a.js
branches:
  only:
  - master
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_6554990e58da_key -iv $encrypted_6554990e58da_iv
  -in xianggang.enc -out ~\/.ssh/xianggang -d