language: node_js

node_js:
- '6'
after_script:
- cd travis
- touch a.js
before_install:
- openssl aes-256-cbc -K $encrypted_6554990e58da_key -iv $encrypted_6554990e58da_iv
  -in xianggang.enc -out ~\/.ssh/xianggang -d
